### ISSUE TITLE
Feature: Remove background colour

### ISSUE THREAD

**Issue by Andonome** [timdubbins/tap#9]
The black background feels quite jarring when everything else appears light (seeing white writing on a black background doesn't work well in Sunlight).

Could there be some option to remove the background colours and simply use the terminal's default colours?

**Comment by timdubbins** [comment]
Hi, thanks for the suggestion.

Yeah, I think we could add something like this. I want to add an option for user-defined colours, an option for using the default colours from the terminal would make a nice addition to this. 

BTW, do the colours look similar to the screenshot in the readme? Just wondered because there should be very little white (just the highlighted line and progress bar times)

**Comment by Andonome** [comment]
They probably would look similar, but some of my local changes persist.

![image](https://github.com/timdubbins/tap/assets/52453904/e0090203-282c-4eff-88a3-e45c1974f59e)

**Comment by timdubbins** [comment]
This feature has been added in v0.4.8.

You can use the terminal background color with the `-b` `--term-bg` flag. 

I also added `--color` to set your own color scheme (example  [here](https://github.com/timdubbins/tap#notes)) and a `-c` `--term_color` flag to use the terminal background and foreground colors only

**Comment by Andonome** [comment]
> This feature has been added in v0.4.8.

Outstanding.

It looks beautiful.
